// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBlzZoezXtjyfC0HtrPhwVWuxAkjZPwG8Q',
    appId: '1:342813350391:web:1c3686285eff4c1b13b6f2',
    messagingSenderId: '342813350391',
    projectId: 'flutter-pro-app-2026',
    authDomain: 'flutter-pro-app-2026.firebaseapp.com',
    storageBucket: 'flutter-pro-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyByqe5Jxh2fLrrmU17IyMSJzBXhLoST4-k',
    appId: '1:342813350391:android:3869bc77ff3df87413b6f2',
    messagingSenderId: '342813350391',
    projectId: 'flutter-pro-app-2026',
    storageBucket: 'flutter-pro-app-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbee1JN8mysgV2fISh1jslVQUSSoClvBs',
    appId: '1:342813350391:ios:44a063bd16a5862e13b6f2',
    messagingSenderId: '342813350391',
    projectId: 'flutter-pro-app-2026',
    storageBucket: 'flutter-pro-app-2026.firebasestorage.app',
    iosBundleId: 'com.example.flutterPro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBlzZoezXtjyfC0HtrPhwVWuxAkjZPwG8Q',
    appId: '1:342813350391:web:1234a03a6aa2b1f113b6f2',
    messagingSenderId: '342813350391',
    projectId: 'flutter-pro-app-2026',
    authDomain: 'flutter-pro-app-2026.firebaseapp.com',
    storageBucket: 'flutter-pro-app-2026.firebasestorage.app',
  );
}
